name: mo3tv
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 5.3.1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  intl: any
  hive: ^2.2.3
  dartz: ^0.10.1
  envied: ^0.5.4+1
  get_it: ^7.7.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  go_router: ^14.2.0
  restart_app: ^1.2.1
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.6
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  gallery_saver_updated: ^3.0.0
  youtube_player_flutter: ^9.0.1
  internet_connection_checker: ^1.0.0+1
dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/mo3tv.png
  adaptive_icon_background: "#000000"
  adaptive_icon_forground: assets/images/mo3tv.png
flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#131314"
  branding: assets/images/poweredby.png
  branding_mode: bottom
flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/
    - assets/images/on_boarding/
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        weight: 900
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        weight: 100