name: mo3tv
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.9.9+4
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.2
  font_awesome_flutter: ^10.4.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.1
  carousel_slider: ^4.2.1
  get_it: ^7.6.0
  dartz: ^0.10.1
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.5
  gallery_saver: ^2.3.2
  go_router: ^7.0.1
  youtube_player_iframe: any
  webview_flutter: any
  flutter_native_splash: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/mo3tv.png
  adaptive_icon_background: "#000000"
  adaptive_icon_forground: assets/images/mo3tv.png

flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#000000"
  branding: assets/images/poweredby.png
  branding_mode: bottom
flutter:
  uses-material-design: true
  assets:
    - assets/images/movieplaceholder.png
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        weight: 900
      - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        weight: 800
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        weight: 100
      - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
        weight: 100
        style: italic